
# **Try**   
- Código que pode gerar um erro.  
# **Catch**  
- Código para tratamento de erros.  
# **Finally**  
- Código de execução obrigatória.


# Sintaxe
try { // Código que pode lançar uma exceção }
catch (ExceptionType ex) { // Código para tratar a exceção } 
finally { // Código que sempre é executado, independentemente de uma exceção ser lançada ou não }

# Funções do ex
| Propriedade/Método | Descrição                                                                                          |
|--------------------|----------------------------------------------------------------------------------------------------|
| ToString()         | Imprime o tipo de exceção, seguido da mensagem e StackTrace.                                       |
| Message            | Uma breve descrição do erro.                                                                       |
| Source             | A aplicação onde a exceção ocorreu.                                                                |
| StackTrace         | A lista dos métodos na pilha atual. Útil para rastrear o caminho que causou a exceção.              |
| TargetSite         | O método que lançou a exceção.                                                                      |
| InnerException     | A exceção que causou a exceção atual. Muitas vezes, as exceções são envolvidas no interior de outras exceções de nível superior. |
| HelpLink           | Um link para um arquivo de ajuda, muitas vezes na forma de uma URL.                                |
| Data               | Pares chave-valor de exceções específicas que fornecem mais informações.                           |

# Throw
- Sintaxe: 
	- throw new ExceptionType("Mensagem de erro");
- **Explicação:** 
	- `throw` é usado para lançar uma exceção e sinalizar um erro que ocorreu no código.
- Exemplo
	public void ProcessData(int value)
	{
	    try
	    {
	        if (value < 0)
	        {
	            throw new ArgumentException("O valor não pode ser negativo.");
	        }
	        // Código para processar dados
	    }
	    catch (ArgumentException ex)
	    {
	        Console.WriteLine($"Erro: {ex.Message}");
	    }
	}
	
